language: julia

os:
  - osx
  - linux

julia:
  - 1.0
  - nightly

script:
  - julia --project -e 'using Pkg;
                        Pkg.add([PackageSpec(name = "TerminalRegressionTests", rev = "master"),
                                 PackageSpec(name = "VT100", rev = "master")]);
                        Pkg.build();
                        Pkg.test()'

 matrix:
   allow_failures:
   - julia: nightly

notifications:
  email: false
