language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.1
  - nightly

script:
  - julia --project --color=yes -e 'using Pkg;
                        Pkg.instantiate();
                        Pkg.add([PackageSpec(name = "TerminalRegressionTests", rev = "master"),
                                 PackageSpec(name = "VT100", rev = "master")]);
                        Pkg.build();
                        Pkg.test()'

matrix:
   allow_failures:
   - julia: nightly

notifications:
  email: false
