language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.1
  - nightly

notifications:
  email: false

script:
  - julia --project --color=yes -e 'using Pkg;
                        Pkg.instantiate();
                        Pkg.add([PackageSpec(name = "TerminalRegressionTests", rev = "master"),
                                 PackageSpec(name = "VT100", rev = "master")]);
                        Pkg.build();
                        Pkg.test()'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.build()'
        - julia --project=docs/ docs/make.jl
      name: "HTML"
      after_success: skip
